// Package swaggerdocs Code generated by swaggo/swag. DO NOT EDIT
package swaggerdocs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GoDNS Support",
            "url": "https://github.com/rogerwesterbo/godns",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/rogerwesterbo/godns/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/cache/clear": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Clear all entries from the DNS response cache",
                "tags": [
                    "Admin"
                ],
                "summary": "Clear DNS cache",
                "responses": {
                    "204": {
                        "description": "Cache cleared successfully"
                    },
                    "503": {
                        "description": "Cache service not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/admin/cache/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get detailed statistics about DNS response caching",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get cache statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.CacheStatsDetailed"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/healthcheck/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get detailed health check results for all monitored backends",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get health check statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.HealthCheckStats"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/loadbalancer/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get detailed statistics about load balancing including backend health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get load balancer statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.LoadBalancerStats"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/querylog/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get statistics about DNS queries including cache hit rate and blocked queries",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get query log statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.QueryLogStats"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/ratelimiter/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get statistics about rate limiting including active limiters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get rate limiter statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.RateLimiterStats"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get comprehensive statistics about DNS caching, rate limiting, load balancing, health checks, and query logging",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get system statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.SystemStats"
                        }
                    }
                }
            }
        },
        "/api/v1/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Export all DNS zones in a specified format (coredns, powerdns, bind, zonefile)",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Export"
                ],
                "summary": "Export all zones",
                "parameters": [
                    {
                        "type": "string",
                        "default": "bind",
                        "description": "Export format: coredns, powerdns, bind, or zonefile",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exported zone configuration",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/export/{zone}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Export a specific DNS zone in a specified format",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Export"
                ],
                "summary": "Export a specific zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "bind",
                        "description": "Export format: coredns, powerdns, bind, or zonefile",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exported zone configuration",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Zone not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Search across DNS zones and records with optional type filtering",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Search DNS zones and records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query (case-insensitive)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "zone",
                                "record"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by result type (zone, record). Can specify multiple types.",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Search results",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_services_v1searchservice.SearchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/zones": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get a list of all DNS zones",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "List all DNS zones",
                "responses": {
                    "200": {
                        "description": "List of zones",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSZone"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Create a new DNS zone with optional records",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "Create a new DNS zone",
                "parameters": [
                    {
                        "description": "Zone to create",
                        "name": "zone",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSZone"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Zone created",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSZone"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Zone already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/zones/{zone}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get a specific DNS zone by name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "Get a DNS zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Zone details",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSZone"
                        }
                    },
                    "404": {
                        "description": "Zone not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update an existing DNS zone (replaces all records)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "Update a DNS zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated zone data",
                        "name": "zone",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSZone"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Zone updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSZone"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Zone not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete a DNS zone and all its records",
                "tags": [
                    "Zones"
                ],
                "summary": "Delete a DNS zone",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Zone deleted"
                    },
                    "404": {
                        "description": "Zone not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/zones/{zone}/records": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Add a new DNS record to an existing zone",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Records"
                ],
                "summary": "Create a DNS record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Record to create",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Record created",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Zone not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Record already exists",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/zones/{zone}/records/{name}/{type}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Get a specific DNS record by name and type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Records"
                ],
                "summary": "Get a DNS record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record name (e.g., www.example.lan.)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record type (e.g., A, AAAA, CNAME)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Record details",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                        }
                    },
                    "404": {
                        "description": "Zone or record not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Update an existing DNS record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Records"
                ],
                "summary": "Update a DNS record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record name (e.g., www.example.lan.)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record type (e.g., A, AAAA, CNAME)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated record data",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Record updated",
                        "schema": {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Zone or record not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Delete a specific DNS record from a zone",
                "tags": [
                    "Records"
                ],
                "summary": "Delete a DNS record",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record name (e.g., www.example.lan.)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record type (e.g., A, AAAA, CNAME)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Record deleted"
                    },
                    "404": {
                        "description": "Zone or record not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/zones/{zone}/records/{name}/{type}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Enable or disable a specific DNS record",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Records"
                ],
                "summary": "Set DNS record status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record name (e.g., www.example.lan.)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Record type (e.g., A, AAAA, CNAME)",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Record status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "enabled": {
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Record status updated"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Zone or record not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/zones/{zone}/status": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "OAuth2Password": []
                    }
                ],
                "description": "Enable or disable a DNS zone",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Zones"
                ],
                "summary": "Set zone status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Zone name (e.g., example.lan)",
                        "name": "zone",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status object with 'enabled' field",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Zone status updated"
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Zone not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_rogerwesterbo_godns_internal_models.DNSRecord": {
            "type": "object",
            "properties": {
                "caa_flags": {
                    "description": "CAA record specific fields",
                    "type": "integer",
                    "example": 0
                },
                "caa_tag": {
                    "description": "Property tag (issue, issuewild, iodef)",
                    "type": "string",
                    "example": "issue"
                },
                "caa_value": {
                    "description": "Property value",
                    "type": "string",
                    "example": "letsencrypt.org"
                },
                "disabled": {
                    "description": "Whether the record is disabled (not served by DNS)",
                    "type": "boolean"
                },
                "mx_host": {
                    "description": "Mail server hostname",
                    "type": "string",
                    "example": "mail.example.com."
                },
                "mx_priority": {
                    "description": "MX record specific fields",
                    "type": "integer",
                    "example": 10
                },
                "name": {
                    "description": "Common fields for all record types",
                    "type": "string",
                    "example": "www.example.lan."
                },
                "soa_expire": {
                    "description": "Expire time (seconds)",
                    "type": "integer",
                    "example": 604800
                },
                "soa_minimum": {
                    "description": "Minimum TTL (seconds)",
                    "type": "integer",
                    "example": 300
                },
                "soa_mname": {
                    "description": "SOA record specific fields",
                    "type": "string",
                    "example": "ns1.example.com."
                },
                "soa_refresh": {
                    "description": "Refresh interval (seconds)",
                    "type": "integer",
                    "example": 3600
                },
                "soa_retry": {
                    "description": "Retry interval (seconds)",
                    "type": "integer",
                    "example": 1800
                },
                "soa_rname": {
                    "description": "Responsible person email",
                    "type": "string",
                    "example": "hostmaster.example.com."
                },
                "soa_serial": {
                    "description": "Serial number (YYYYMMDDnn)",
                    "type": "integer",
                    "example": 2024110601
                },
                "srv_port": {
                    "description": "Port number (0-65535)",
                    "type": "integer",
                    "example": 443
                },
                "srv_priority": {
                    "description": "SRV record specific fields",
                    "type": "integer",
                    "example": 10
                },
                "srv_target": {
                    "description": "Target hostname",
                    "type": "string",
                    "example": "server.example.com."
                },
                "srv_weight": {
                    "description": "Weight for load balancing (0-65535)",
                    "type": "integer",
                    "example": 60
                },
                "ttl": {
                    "description": "Time to live in seconds",
                    "type": "integer",
                    "example": 300
                },
                "type": {
                    "description": "A, AAAA, MX, NS, TXT, SRV, SOA, CAA, CNAME, ALIAS, PTR",
                    "type": "string",
                    "example": "A"
                },
                "value": {
                    "description": "Simple value field (for A, AAAA, CNAME, ALIAS, NS, PTR, TXT)",
                    "type": "string",
                    "example": "192.168.1.100"
                }
            }
        },
        "github_com_rogerwesterbo_godns_internal_models.DNSZone": {
            "type": "object",
            "properties": {
                "domain": {
                    "description": "e.g., \"example.lan.\"",
                    "type": "string",
                    "example": "example.lan."
                },
                "enabled": {
                    "description": "Whether the zone is enabled/active",
                    "type": "boolean"
                },
                "records": {
                    "description": "DNS records in this zone",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                    }
                }
            }
        },
        "github_com_rogerwesterbo_godns_internal_services_v1searchservice.SearchResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "Number of results found",
                    "type": "integer",
                    "example": 5
                },
                "query": {
                    "description": "The search query",
                    "type": "string",
                    "example": "example"
                },
                "results": {
                    "description": "List of search results",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_services_v1searchservice.SearchResult"
                    }
                }
            }
        },
        "github_com_rogerwesterbo_godns_internal_services_v1searchservice.SearchResult": {
            "type": "object",
            "properties": {
                "record": {
                    "description": "Record details (if type is record)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_models.DNSRecord"
                        }
                    ]
                },
                "type": {
                    "description": "Type of result (zone, record)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_rogerwesterbo_godns_internal_services_v1searchservice.SearchResultType"
                        }
                    ],
                    "example": "zone"
                },
                "zone": {
                    "description": "Zone name",
                    "type": "string",
                    "example": "example.lan"
                }
            }
        },
        "github_com_rogerwesterbo_godns_internal_services_v1searchservice.SearchResultType": {
            "type": "string",
            "enum": [
                "zone",
                "record"
            ],
            "x-enum-varnames": [
                "SearchResultTypeZone",
                "SearchResultTypeRecord"
            ]
        },
        "internal_httpserver_handlers_v1adminhandler.CacheStats": {
            "type": "object",
            "properties": {
                "current_size": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "hit_rate": {
                    "type": "string"
                },
                "max_size": {
                    "type": "integer"
                },
                "ttl_minutes": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.CacheStatsDetailed": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "evictions": {
                    "type": "integer"
                },
                "hit_rate": {
                    "type": "number"
                },
                "hits": {
                    "type": "integer"
                },
                "misses": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.HealthCheckResultInfo": {
            "type": "object",
            "properties": {
                "error_message": {
                    "type": "string"
                },
                "healthy": {
                    "type": "boolean"
                },
                "last_check": {
                    "type": "string"
                },
                "last_failure": {
                    "type": "string"
                },
                "last_success": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.HealthCheckStats": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "interval_seconds": {
                    "type": "integer"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.HealthCheckResultInfo"
                    }
                },
                "timeout_seconds": {
                    "type": "integer"
                },
                "total_targets": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.LoadBalancerBackendInfo": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "healthy": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.LoadBalancerStats": {
            "type": "object",
            "properties": {
                "backend_groups": {
                    "type": "integer"
                },
                "backends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.LoadBalancerBackendInfo"
                    }
                },
                "enabled": {
                    "type": "boolean"
                },
                "healthy_backends": {
                    "type": "integer"
                },
                "strategy": {
                    "type": "string"
                },
                "total_backends": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.QueryLogStats": {
            "type": "object",
            "properties": {
                "blocked_queries": {
                    "type": "integer"
                },
                "blocked_rate": {
                    "type": "number"
                },
                "cache_hit_rate": {
                    "type": "number"
                },
                "cached_queries": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "total_queries": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.RateLimiterStats": {
            "type": "object",
            "properties": {
                "active_limiters": {
                    "type": "integer"
                },
                "burst": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "qps": {
                    "type": "integer"
                },
                "total_blocked": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver_handlers_v1adminhandler.SystemStats": {
            "type": "object",
            "properties": {
                "cache": {
                    "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.CacheStats"
                },
                "health_check": {
                    "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.HealthCheckStats"
                },
                "load_balancer": {
                    "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.LoadBalancerStats"
                },
                "query_log": {
                    "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.QueryLogStats"
                },
                "rate_limiter": {
                    "$ref": "#/definitions/internal_httpserver_handlers_v1adminhandler.RateLimiterStats"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "OAuth2Password": {
            "type": "oauth2",
            "flow": "password",
            "tokenUrl": "http://localhost:14101/realms/godns/protocol/openid-connect/token"
        }
    },
    "tags": [
        {
            "description": "Health check and readiness endpoints",
            "name": "Health"
        },
        {
            "description": "DNS zone management operations",
            "name": "Zones"
        },
        {
            "description": "DNS record management operations",
            "name": "Records"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:14000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GoDNS API",
	Description:      "RESTful API for managing DNS zones and records in GoDNS\n\nThis API provides CRUD operations for DNS zones and records, storing data in Valkey (Redis-compatible).\n\n## Features\n- Create, read, update, and delete DNS zones\n- Manage individual DNS records within zones\n- Support for various record types (A, AAAA, CNAME, MX, NS, TXT, PTR, SRV, SOA, CAA)\n- Health and readiness endpoints for Kubernetes deployments\n\n## Authentication\nThis API uses OAuth2/JWT authentication via Keycloak.\n\nTo authenticate:\n1. Click \"Authorize\" button\n2. For BearerAuth: Enter \"Bearer YOUR_JWT_TOKEN\"\n3. For OAuth2: Enter credentials (testuser/password for development)\n\nTo get a token manually:\n```\ncurl -X POST \"http://localhost:14101/realms/godns/protocol/openid-connect/token\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"client_id=godns-cli\" -d \"username=testuser\" -d \"password=password\" -d \"grant_type=password\"\n```\n\nExtract and use the access_token:\n```\nTOKEN=$(curl -s -X POST \"http://localhost:14101/realms/godns/protocol/openid-connect/token\" -H \"Content-Type: application/x-www-form-urlencoded\" -d \"client_id=godns-cli\" -d \"username=testuser\" -d \"password=password\" -d \"grant_type=password\" | jq -r '.access_token')\n\ncurl -H \"Authorization: Bearer $TOKEN\" http://localhost:14000/api/v1/zones\n```\n\nUse HTTPS (port 14102) for production.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
