package consts

var (
	DEVELOPMENT = "DEVELOPMENT"

	LOG_LEVEL              = "LOG_LEVEL"
	LOG_JSON               = "LOG_JSON"
	LOG_ADD_CALLER         = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE = "LOG_DISABLE_STACKTRACE"
	LOG_COLORIZE_LINE      = "LOG_COLORIZE_LINE"
	LOG_UNESCAPE_MULTILINE = "LOG_UNESCAPE_MULTILINE"

	DNS_SERVER_PORT                 = "DNS_SERVER_PORT"
	DNS_SERVER_LIVENESS_PROBE_PORT  = "DNS_SERVER_LIVENESS_PROBE_PORT"
	DNS_SERVER_READYNESS_PROBE_PORT = "DNS_SERVER_READYNESS_PROBE_PORT"
	DNS_UPSTREAM_SERVER             = "DNS_UPSTREAM_SERVER"
	DNS_ENABLE_HTTP_API             = "DNS_ENABLE_HTTP_API"

	HTTP_API_PORT                 = "HTTP_API_PORT"
	HTTP_API_LIVENESS_PROBE_PORT  = "HTTP_API_LIVENESS_PROBE_PORT"
	HTTP_API_READINESS_PROBE_PORT = "HTTP_API_READINESS_PROBE_PORT"
	HTTP_API_CORS_ALLOWED_ORIGINS = "HTTP_API_CORS_ALLOWED_ORIGINS"

	VALKEY_HOST     = "VALKEY_HOST"
	VALKEY_PORT     = "VALKEY_PORT"
	VALKEY_USERNAME = "VALKEY_USERNAME"
	VALKEY_TOKEN    = "VALKEY_TOKEN"

	VALKEY_MAX_RETRIES            = "VALKEY_MAX_RETRIES"
	VALKEY_INITIAL_RETRY_DELAY_MS = "VALKEY_INITIAL_RETRY_DELAY_MS"

	// Authentication / Keycloak settings
	AUTH_ENABLED            = "AUTH_ENABLED"
	KEYCLOAK_URL            = "KEYCLOAK_URL"
	KEYCLOAK_REALM          = "KEYCLOAK_REALM"
	KEYCLOAK_API_CLIENT_ID  = "KEYCLOAK_API_CLIENT_ID"
	KEYCLOAK_CLI_CLIENT_ID  = "KEYCLOAK_CLI_CLIENT_ID"
	KEYCLOAK_ADMIN_USER     = "KEYCLOAK_ADMIN_USER"
	KEYCLOAK_ADMIN_PASSWORD = "KEYCLOAK_ADMIN_PASSWORD"
)
