package consts

var (
	DEVELOPMENT = "DEVELOPMENT"

	LOG_LEVEL              = "LOG_LEVEL"
	LOG_JSON               = "LOG_JSON"
	LOG_ADD_CALLER         = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE = "LOG_DISABLE_STACKTRACE"
	LOG_COLORIZE_LINE      = "LOG_COLORIZE_LINE"
	LOG_UNESCAPE_MULTILINE = "LOG_UNESCAPE_MULTILINE"

	DNS_SERVER_PORT                 = "DNS_SERVER_PORT"
	DNS_SERVER_LIVENESS_PROBE_PORT  = "DNS_SERVER_LIVENESS_PROBE_PORT"
	DNS_SERVER_READYNESS_PROBE_PORT = "DNS_SERVER_READYNESS_PROBE_PORT"
	DNS_UPSTREAM_SERVER             = "DNS_UPSTREAM_SERVER"

	VALKEY_HOST     = "VALKEY_HOST"
	VALKEY_PORT     = "VALKEY_PORT"
	VALKEY_USERNAME = "VALKEY_USERNAME"
	VALKEY_TOKEN    = "VALKEY_TOKEN"

	VALKEY_MAX_RETRIES            = "VALKEY_MAX_RETRIES"
	VALKEY_INITIAL_RETRY_DELAY_MS = "VALKEY_INITIAL_RETRY_DELAY_MS"
)
